### PR TITLE
Add tornado support

### PR DESCRIPTION
**Pull request by mkn8rd**

### CODE REVIEW

**Comment by mkn8rd** [comment]
@olucurious could you review my pull request, please? :)

**Comment by olucurious** [comment]
I'm so sorry it took a while to respond.

The funny thing is I even use tornado almost every single day.
Thanks so much for this.

**Comment by olucurious** [comment]
I'm about to merge to the master branch but I'm thinking we should add tornado to __install_requires__, but at the same time I guessing anyone that will attempt to use TornadoFCMNotification must have installed tornado.

I guess I'll just merge anyway.
Thanks again.

**Comment by mkn8rd** [comment]
@olucurious yes I thought about adding tornado to requirements and decided the same thing. Thank you for quick reaction! :) Hope that code would be helpful for someone else.

**Comment by mkn8rd** [comment]
@olucurious also what's have to be done for the package to be updated to 1.0.1 on pypi?..

**Comment by olucurious** [comment]
Done.

**Comment by mkn8rd** [comment]
@olucurious something wrong with 1.0.1 package on pypi: there's no `extensions` dir at all in `pyfcm-1.0.1.tar.gz` :( Could you please check what actually happened?..

**Comment by olucurious** [comment]
You didn't add the folder to the manifest file.

Fixed here: https://github.com/olucurious/PyFCM/pull/40/commits/72bfc8c3ef2ba7f4e42bcc8fab1687667e5b4904

**Comment by mkn8rd** [comment]
@olucurious ah.. sorry then. Thank you for the fix.

**Pull request merged**
